config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  resources :posts do
  	resources :comments, only: [:create]
  end
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :post_image, PostImageUploader
    belongs_to :user
    has_many :comments, as: :commentable

    validates :title, :description, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments

  validates :email, :password, presence: true

  def name
  	self.email.split("@").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :comment_params
  def create
  	post = Post.find(params["post_id"])
  	comment = post.comments.new(comment_params)
  	comment.user_id = current_user.id
  	comment.save!
  	redirect_to post_path(post)
  end

  private

  def comment_params
  	params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :post_users_only_edit_and_destroy, only: [:edit, :destroy, :update]

  def index
    @posts = current_user.posts.all
  end

  def show
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id, :post_image)
    end

    def post_users_only_edit_and_destroy
      post = Post.find(params[:id].to_i)
      if current_user.posts.include? post
        return true
      else
        flash[:notice] = 'You can\'t access this post'
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@posts = Post.all
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
        <a class="navbar-brand" href="/"><strong>Aknamed</strong></a>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
       
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right" id="nav_links">
        <li><a href="#"><i class="fa fa-lg fa-dot-circle-o"></i></a></li>
        <% if !user_signed_in? %>
            <li><a href="/about">About</a></li>
            <li><a href="/users/sign_in">Sign in</a></li>
        <% else %>
            <li><a href="/posts/new">Create post</a></li>
            <li><a href="/">Posts</a></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aknamed</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:300,400,500,700|Sen&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= render partial: 'layouts/nav' %>
    <div class="container">
    
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>


      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, html: { id: "post_form_validation"}) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :post_image %>
    <%= form.file_field :post_image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control required" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.trix_editor :description, class: "form-control required" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="row text-center">
	<h3>Edit post</h3>
</div>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form', post: @post %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="row">
  
</div>

app/views/posts/new.html.erb
<div class="row text-center">
	<h3>Create post</h3>
</div>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form', post: @post %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="row">
			<h1 class="post_title"><strong><%= @post.title %></strong></h1>
		</div>
		
		<div class="row post_user_info">
			<hr>
			<p><%= @post.user.name %></p>
			<p><%= @post.created_at.strftime("%Y-%m-%d") %></p>
			<hr>
		</div>

		<div class="row">
			<% if @post.post_image.present? %>
				<%= image_tag @post.post_image.url, class: "img-responsive" %>
			<% else %>
				<img src="https://images.pexels.com/photos/807623/pexels-photo-807623.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" align="post image not found" class="img-responsive">
				
			<% end %>
		</div>

		<div class="row post_description">
			<p>
				<%= raw @post.description %>
			</p>
		</div>
		<% if user_signed_in? and @post.user.present? %>
			<div class="row">
				<hr>
					<%= link_to "Edit", edit_post_path(@post),  class: "btn btn-warning" %>&emsp; <%= link_to "Destroy", post_path(@post), method: :delete, class: "btn btn-danger" %>
				<hr>
			</div>
		<% end %>
		<div class="row">
			<% if @post.comments.present? %>
				<% @comments.each do |comment| %>
					<p><strong><%= comment.user.name %></strong></p>
					<p><%= comment.body %></p>
					<br>
				<% end %>
			<% else %>
				<p class="text-center">
					Comments not found.
				</p>
			<% end %>
			<hr>
		</div>

		<div class="row">
			<%= form_for :comment, url: post_comments_path(@post), method: :post do |f| %>
				<div class="form-group">
					<%= f.text_area :body, class: "form-control", placeholder: "Comment body" %>
					<%#= f.hidden_fiel :post_id, value: @post.id %>
				</div>
				<div class="form-group">
					<%= f.submit "Create comment", class: "btn btn-primary" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/static_pages/about.html.erb
<div class="container">
	<div class="row">
		<div class="text-center mtb-4">
			<h1>Akna Medical Private Limited</h1>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
	<header class="text-center mtb-4">
		<h1>Aknamed Blog<h1>
	</header>
</div>
<div class="row">
	<% @posts.each do |post| %>
		<div class="col-md-3">
			<div id="small_description_text">
				<h1 id="small_title_text"><%= link_to post.title, post_path(post) %></h1>
				<hr>
				<p>
					<%= post.user.name.capitalize %>&emsp;<%= post.created_at.strftime("%Y-%m-%d") %>
				</p>
				<hr>
			</div>
		</div>
	<% end %>
</div>